CREATE TABLE Billetter(
id SERIAL NOT NULL,
filmer VARCHAR(255) NOT NULL,
antall VARCHAR(255) NOT NULL,
fnavn VARCHAR(255) NOT NULL,
enavn VARCHAR(255) NOT NULL,
tlf VARCHAR(255) NOT NULL,
epost VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);